// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file FrameMSG.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "FrameMSG.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

FrameMSG::FrameMSG()
{
    // m_width com.eprosima.idl.parser.typecode.PrimitiveTypeCode@4d9e68d0
    m_width = 0;
    // m_height com.eprosima.idl.parser.typecode.PrimitiveTypeCode@42e99e4a
    m_height = 0;
    // m_step com.eprosima.idl.parser.typecode.PrimitiveTypeCode@14dd9eb7
    m_step = 0;
    // m_timestamp com.eprosima.idl.parser.typecode.PrimitiveTypeCode@52e6fdee
    m_timestamp = 0;
    // m_encoding com.eprosima.idl.parser.typecode.StringTypeCode@6c80d78a
    m_encoding ="";
    // m_data com.eprosima.idl.parser.typecode.SequenceTypeCode@62150f9e


}

FrameMSG::~FrameMSG()
{





}

FrameMSG::FrameMSG(
        const FrameMSG& x)
{
    m_width = x.m_width;
    m_height = x.m_height;
    m_step = x.m_step;
    m_timestamp = x.m_timestamp;
    m_encoding = x.m_encoding;
    m_data = x.m_data;
}

FrameMSG::FrameMSG(
        FrameMSG&& x)
{
    m_width = x.m_width;
    m_height = x.m_height;
    m_step = x.m_step;
    m_timestamp = x.m_timestamp;
    m_encoding = std::move(x.m_encoding);
    m_data = std::move(x.m_data);
}

FrameMSG& FrameMSG::operator =(
        const FrameMSG& x)
{

    m_width = x.m_width;
    m_height = x.m_height;
    m_step = x.m_step;
    m_timestamp = x.m_timestamp;
    m_encoding = x.m_encoding;
    m_data = x.m_data;

    return *this;
}

FrameMSG& FrameMSG::operator =(
        FrameMSG&& x)
{

    m_width = x.m_width;
    m_height = x.m_height;
    m_step = x.m_step;
    m_timestamp = x.m_timestamp;
    m_encoding = std::move(x.m_encoding);
    m_data = std::move(x.m_data);

    return *this;
}

bool FrameMSG::operator ==(
        const FrameMSG& x) const
{

    return (m_width == x.m_width && m_height == x.m_height && m_step == x.m_step && m_timestamp == x.m_timestamp && m_encoding == x.m_encoding && m_data == x.m_data);
}

bool FrameMSG::operator !=(
        const FrameMSG& x) const
{
    return !(*this == x);
}

size_t FrameMSG::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (65536 * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);




    return current_alignment - initial_alignment;
}

size_t FrameMSG::getCdrSerializedSize(
        const FrameMSG& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.encoding().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.data().size() > 0)
    {
        current_alignment += (data.data().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }




    return current_alignment - initial_alignment;
}

void FrameMSG::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_width;
    scdr << m_height;
    scdr << m_step;
    scdr << m_timestamp;
    scdr << m_encoding;
    scdr << m_data;

}

void FrameMSG::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_width;
    dcdr >> m_height;
    dcdr >> m_step;
    dcdr >> m_timestamp;
    dcdr >> m_encoding;
    dcdr >> m_data;
}

/*!
 * @brief This function sets a value in member width
 * @param _width New value for member width
 */
void FrameMSG::width(
        int32_t _width)
{
    m_width = _width;
}

/*!
 * @brief This function returns the value of member width
 * @return Value of member width
 */
int32_t FrameMSG::width() const
{
    return m_width;
}

/*!
 * @brief This function returns a reference to member width
 * @return Reference to member width
 */
int32_t& FrameMSG::width()
{
    return m_width;
}

/*!
 * @brief This function sets a value in member height
 * @param _height New value for member height
 */
void FrameMSG::height(
        int32_t _height)
{
    m_height = _height;
}

/*!
 * @brief This function returns the value of member height
 * @return Value of member height
 */
int32_t FrameMSG::height() const
{
    return m_height;
}

/*!
 * @brief This function returns a reference to member height
 * @return Reference to member height
 */
int32_t& FrameMSG::height()
{
    return m_height;
}

/*!
 * @brief This function sets a value in member step
 * @param _step New value for member step
 */
void FrameMSG::step(
        int32_t _step)
{
    m_step = _step;
}

/*!
 * @brief This function returns the value of member step
 * @return Value of member step
 */
int32_t FrameMSG::step() const
{
    return m_step;
}

/*!
 * @brief This function returns a reference to member step
 * @return Reference to member step
 */
int32_t& FrameMSG::step()
{
    return m_step;
}

/*!
 * @brief This function sets a value in member timestamp
 * @param _timestamp New value for member timestamp
 */
void FrameMSG::timestamp(
        int32_t _timestamp)
{
    m_timestamp = _timestamp;
}

/*!
 * @brief This function returns the value of member timestamp
 * @return Value of member timestamp
 */
int32_t FrameMSG::timestamp() const
{
    return m_timestamp;
}

/*!
 * @brief This function returns a reference to member timestamp
 * @return Reference to member timestamp
 */
int32_t& FrameMSG::timestamp()
{
    return m_timestamp;
}

/*!
 * @brief This function copies the value in member encoding
 * @param _encoding New value to be copied in member encoding
 */
void FrameMSG::encoding(
        const std::string& _encoding)
{
    m_encoding = _encoding;
}

/*!
 * @brief This function moves the value in member encoding
 * @param _encoding New value to be moved in member encoding
 */
void FrameMSG::encoding(
        std::string&& _encoding)
{
    m_encoding = std::move(_encoding);
}

/*!
 * @brief This function returns a constant reference to member encoding
 * @return Constant reference to member encoding
 */
const std::string& FrameMSG::encoding() const
{
    return m_encoding;
}

/*!
 * @brief This function returns a reference to member encoding
 * @return Reference to member encoding
 */
std::string& FrameMSG::encoding()
{
    return m_encoding;
}
/*!
 * @brief This function copies the value in member data
 * @param _data New value to be copied in member data
 */
void FrameMSG::data(
        const std::vector<uint8_t>& _data)
{
    m_data = _data;
}

/*!
 * @brief This function moves the value in member data
 * @param _data New value to be moved in member data
 */
void FrameMSG::data(
        std::vector<uint8_t>&& _data)
{
    m_data = std::move(_data);
}

/*!
 * @brief This function returns a constant reference to member data
 * @return Constant reference to member data
 */
const std::vector<uint8_t>& FrameMSG::data() const
{
    return m_data;
}

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
std::vector<uint8_t>& FrameMSG::data()
{
    return m_data;
}

size_t FrameMSG::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool FrameMSG::isKeyDefined()
{
    return false;
}

void FrameMSG::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
          
}
